version: '3.8'

services:
  tritonserver:
    image: nvcr.io/nvidia/tritonserver:24.05-py3
    volumes:
      - ./triton/model_repository:/models
    network_mode: host
    command: tritonserver --model-repository=/models

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${FASTAPI_ENV:-development}
    shm_size: 4gb
    restart: always
    ports:
      - "8088:80"
    env_file:
      - .env
    environment:
      - TRITON_SERVER_URL=tritonserver:8001
    depends_on:
      - tritonserver
